# Generated by Django 3.1.4 on 2021-02-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20210206_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartinfo',
            name='season',
            field=models.CharField(choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21')], default='2020-21', max_length=7),
        ),
    ]
