# Generated by Django 3.1.4 on 2021-02-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20210206_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartinfo',
            name='season',
        ),
        migrations.RemoveField(
            model_name='chartinfo',
            name='season_type',
        ),
        migrations.AlterField(
            model_name='chartinfo',
            name='player_name',
            field=models.CharField(default='Ben Simmons', max_length=50),
        ),
        migrations.AlterField(
            model_name='chartinfo',
            name='team',
            field=models.CharField(default='PHI', max_length=3),
        ),
    ]
