# Generated by Django 3.1.7 on 2021-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Ben Simmons', max_length=50)),
                ('team', models.CharField(default='PHI', max_length=3)),
            ],
        ),
    ]
